  app:
    name: Deploy application code
    needs: infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.inputs.ref || 'main' }}

      - name: Configure AWS credentials (Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Zip application code
        run: |
          zip -r /tmp/library-booking-app.zip . \
            -x ".git/*" ".github/*" "infra/*" "uploads/*" "*.md"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Get S3 bucket name from Terraform output
        id: tf-output
        working-directory: infra/envs/sandbox
        run: |
          terraform init -input=false
          echo "bucket=$(terraform output -raw s3_bucket_name)" >> "$GITHUB_OUTPUT"